cards = {
    1: (
        "教",
        "TEACHING",
        "キョウ, おそ-わる, おし-える",
        "Teaching `filial piety> is not something at [the top of the queue (キョウ)] for the `taskmaster>.",
        "",
    ),
    2: (
        "玉",
        "JEWEL, ball",
        "ギョク, たま",
        "The `king> favourite JEWEL is like a sparkling `drop> of pure light which [TAMA (たま) picks up].",
        "Jewel",
    ),
    3: (
        "近",
        "NEAR",
        "キン, ちか-い",
        "When on the `road>, [the KINg (キン) carries his blue] `axe>.",
        "",
    ),
    4: (
        "形",
        "SHAPE",
        "ケイ, ギョウ, かた, かたち",
        "[KAte (ケイ) dressed in blue] checks the `shape> with `two hands>.",
        "",
    ),
    5: (
        "計",
        "PLOT,PLAN, Calculation",
        "ケイ, はか-らう, はか-る",
        "[KAte (ケイ) dressed in blue] PLOTS and PLANS her `words> to hurt like a `needle>.",
        "",
    ),
    6: (
        "元",
        "BEGINNING, origin",
        "ガン, ゲン, もと",
        "She had the BEGINNING of a [MOTTO (もと) tattooed in blue] on her `two> `human legs>.",
        "",
    ),
    7: (
        "原",
        "Meadow",
        "ゲン, はら",
        "The `spring> bubbles up on the `cliff>-side MEADOW [that GANdalf (ゲン) visits in his blue hat].",
        "",
    ),
    8: (
        "戸",
        "DOOR",
        "コ, と",
        "The DOOR had a `flag> on it to indicate it couldn't be opening because it scraped against the `ceiling> due to excess COats (コ) of blue paint].",
        "",
    ),
    9: (
        "古",
        "OLD",
        "コ, ふる-す, ふる-い",
        "He was buried in his OLD [blue COat (コ)] under a gravestone.",
        "",
    ),
    10: (
        "午",
        "NOON",
        "ゴ",
        "At NOON, the zodiac horse [is raring to GO GO GO (ゴ)].",
        "Horse",
    ),
    11: (
        "後",
        "AFTER, BEHIND",
        "ゴ, コウ, のち, あと, うし-ろ, おく-れる",
        "AFTER `walking> the `line> repeatedly the `cocoon> [is ready to GO GO GO (ゴ)].",
        "",
    ),
    12: (
        "語",
        "LANGUAGE, WORD",
        "ゴ, かた-る, かた-らう",
        ".",
        "",
    ),
    13: (
        "工",
        "CRAFT, Construction",
        "コウ, ク",
        "The I-beam was lovingly CRAFTed and finished off with [a blue COAt (コウ) of paint].",
        "I-beam",
    ),
    14: (
        "広",
        "WIDE",
        "コウ, ひろ-める, ひろ-げる, ひろ-まる, ひろ-がる, ひろ-い",
        "The `cave> was WIDE but he still managed to bang his `elbow> against the wall [ruining his blue COAt (コウ)].",
        "",
    ),
    15: (
        "交",
        "MINGLE",
        "コウ, か-う, まじ-わる, ま-じる, ま-ぜる, か-わす, まじ-える, ま-ざる",
        "The `father>'s MINGLE together in their `hat>s and [blue COAts (コウ)].",
        "",
    ),
    16: (
        "光",
        "LIGHT, ray, shine",
        "コウ, ひかり, ひか-る",
        "The LIGHT rays shine on the `little> dust-motes `legs> as they dance in their [the blue COAts (コウ)].",
        "",
    ),
    17: (
        "考",
        "THINK, Consider",
        "コウ, かんが-える",
        "The `old man> THINKs about selling his `slingshot> and buying [the blue COAt (コウ)].",
        "",
    ),
    18: (
        "行",
        "GOING",
        "コウ, アン, ギョウ ゆ-く, い-く, おこな-う",
        "[In his blue COAt (コウ)] he is GOING down the boulevard.",
        "Line or boulevard",
    ),
    19: (
        "高",
        "TALL",
        "コウ, たか-まる, たか, たか-める, たか-い",
        "The loud `mouth> in the top hat stood on the alien's `glass hood> and looked very TALL [in the blue COAt (コウ)].",
        "Tall",
    ),
    20: (
        "黄",
        "YELLOW",
        "コウ, オウ, き, こ",
        "The `salad> turned YELLOW and the `sprout> grew `legs> as time passed, according to [GintoKI (き) in his blue COAt (コウ)]",
        "",
    ),
}
