cards = {
    1: (
        "科",
        "DEPARTMENT",
        "カ",
        "The DEPARTMENT staff used the `measuring cups> to [fill the director's blue CAr (カ)] with `wheat>.",
        "",
    ),
    2: (
        "夏",
        "SUMMER",
        "ゲ, カ, なつ",
        "During the SUMMER, they get it into their `head>s that `walking legs> are [quicker than a blue CAr (カ). I think they are NUTS (なつ)].",
        "",
    ),
    3: (
        "家",
        "HOUSE, FAMILY",
        "ケ, カ, や, いえ",
        "[Blue-haired KEvin's (ケ)] FAMILY `HOUSE> looks fancy from the outside but the `sow> has wrecked the inside.",
        "",
    ),
    4: (
        "歌",
        "SONG",
        "カ, うた, うた-う",
        "[Blue-haired UTA (うた)] `yawn>s while leading the `can>-`can> girls in a SONG.",
        "",
    ),
    5: (
        "画",
        "BRUSH-STROKE, picture",
        "カク, ガ",
        "[Blue-haired GArfield (ガ)] paints a `sprout> on the `ceiling> with BRUSH-STROKEs as wide as a `shovel>.",
        "",
    ),
    6: (
        "回",
        "-TIMES",
        "エ, カイ, まわ-す, まわ-る",
        "[To build the blue KIte (カイ), the Expert (エ)] said to make this square nut go around the square bolt at least ten TIMES.",
        "",
    ),
    7: (
        "会",
        "MEETING",
        "エ, カイ, あ-う",
        "['OW (あ-う)!' he said] when bumping into the `wall> at the `MEETING>.",
        "",
    ),
    8: (
        "海",
        "OCEAN",
        "カイ, うみ",
        "`Every> single `drop of water> ends up in the OCEAN [according to blue-haired KAI (カイ)].",
        "",
    ),
    9: (
        "絵",
        "PICTURE",
        "エ, カイ",
        "At the `meeting>, [the blue-haired twins KAI (カイ) and Emile (エ)] made a wonderful PICTURE out coloured `thread>s.",
        "",
    ),
    10: (
        "貝",
        "SHELLFISH",
        "かい",
        "A SHELLFISH with the big `eye> totters around on its `little legs>. [KAInda (かい) cute, I suppose].",
        "Clams (money)",
    ),
    11: (
        "外",
        "OUTSIDE",
        "ガイ, ゲ, ほか, はず-れる, そと, はず-す",
        "It was `evening> OUTSIDE, so what better time to use one's `magic wand> [thought the GUY (ガイ) in the blue suit].",
        "",
    ),
    12: (
        "間",
        "INTERVAL",
        "ケン, カン あいだ, ま",
        "[When MA (ま) has the blues], she appreciates the INTERVAL when the `day> is over and the `gate> is closed.",
        "",
    ),
    13: (
        "顔",
        "FACE",
        "ガン, かお",
        "You should have seen the `lad>'s FACE when I pointed [the blue GUN (ガン)] at his `head>.",
        "",
    ),
    14: (
        "汽",
        "VAPOUR, steam",
        "キ",
        "The VAPOUR formed `drops of water> which dripped off of the `hook> and landed on [GintoKI (キ)] who was `reclining> on the `floor>.",
        "",
    ),
    15: (
        "記",
        "SCRIBE, record",
        "キ, しる-す",
        "[GintoKI (キ)] SCRIBEd the meaning of the `words> in his `snake>-ish handwriting.",
        "",
    ),
    16: (
        "帰",
        "HOMECOMING",
        "キ, かえ-す, かえ-る",
        "[After GintoKI's (キ)] HOMECOMING, he swapped his `spear> for a `broom> and an `apron>.",
        "",
    ),
    17: (
        "牛",
        "COW",
        "ギュウ, うし",
        "The COW with the broken horn was [called USCHI (うし)].",
        "",
    ),
    18: (
        "魚",
        "FISH",
        "ギョ, さかな, うお",
        "The FISH was `bound> up while he prepared a `cooking fire> by the `rice field>. [Soon it was time for it to GO (ギョ) in the blue pot].",
        "",
    ),
    19: (
        "京",
        "CAPITAL",
        "キョウ, ケイ",
        "When we think of a CAPITAL city [like ToKYO (キョウ)], we think of `tall> buildings with the `little> folk scurrying about their business.",
        "",
    ),
    20: (
        "強",
        "STRONG",
        "キョウ, ゴウ, し-いる, つよ-い, つよ-める, つよ-まる",
        "[ToKYO's (キョウ)] `vast> buildings were STRONG enough to withstand the giant `insect>s.",
        "",
    ),
}
