cards = {
    1: (
        "合",
        "FIT; combine",
        "ガッ, ゴウ, カッ, あ-う, あ-わせる, あ-わす",
        "There was not enough room at the `meeting> to FIT more than one big `mouth> in, so [the one in blue had to GO (ゴウ)].",
        "",
    ),
    2: (
        "谷",
        "VALLEY",
        "コク, たに",
        "[NakaTANI (たに) says when] `going in> to the `mouth> of the VALLEY take an `umbrella>.",
        "",
    ),
    3: (
        "国",
        "COUNTRY",
        "コク, くに",
        "The COUNTRY's prize `jewel> was `walled in> to protect it [from the blue COCKatiels (コク)].",
        "",
    ),
    4: (
        "黒",
        "BLACK",
        "コク, くろ-い, くろ",
        "The `computer> was charred BLACK by the `oven fire> [set by the blue COCKatiels (コク)].",
        "",
    ),
    5: (
        "今",
        "NOW",
        "キン, コン, いま",
        "The `clock hands> showed that the `meeting> was starting NOW; [I was CONcerned (コン) I was late].",
        "",
    ),
    6: (
        "才",
        "GENIUS",
        "サイ",
        "[The crowd SIGHed (サイ) in amazement] as the GENIUS showed he could do it with just one finger.",
        "",
    ),
    7: (
        "作",
        "MAKE",
        "サク, サ, つく-る",
        "The `person> used a `saw> to MAKE it but [it still SUCKed (サク)].",
        "",
    ),
    8: (
        "算",
        "CALCULATION",
        "サン",
        "Using the `bamboo> and `both hands>, in front of my `eye>s he created an abacus for the CALCULATION [of how much blue SANd (サン) we would need].",
        "",
    ),
    9: (
        "止",
        "STOP",
        "シ, と-める, と-まる",
        "When he can to a sudden STOP, he left a footprint [on the blue SHEet (シ)].",
        "Footprint",
    ),
    10: (
        "市",
        "CITY; MARKET",
        "シ, いち",
        "It is MARKET day in the CITY, so dressed only in only a bath `towel> and `top hat> I rushed there [to buy a blue SHEet (シ)].",
        "",
    ),
    11: (
        "思",
        "THINK; remember",
        "シ, おも-う",
        "THINKing happens somewhere between the `brain> and `heart> [for SHEena (シ) dressed in blue].",
        "",
    ),
    12: (
        "紙",
        "PAPER",
        "シ, かみ",
        "[For SHEena's (シ) sake] the PAPER described the `thread> leading back to the origin of her `surname>.",
        "",
    ),
    13: (
        "寺",
        "BUDDIST TEMPLE",
        "ジ, てら",
        "[According to the TERAdas (てら)] the TEMPLE was built by `gluing> it to the `dirt>.",
        "",
    ),
    14: (
        "自",
        "ONESELF",
        "シ, ジ, みずか-ら",
        "A little `drop> of a nose between the `eye>s is where to point when referring to ONESELF [in conversation at the GYm (ジ)].",
        "Nose",
    ),
    15: (
        "時",
        "TIME",
        "ジ, とき",
        "[The guy at the GYm (ジ) says that] TIME is determined by the `sun>'s position over the temple>.",
        "",
    ),
    16: (
        "室",
        "ROOM",
        "シツ, むろ",
        "[The blue SHITSU's (シツ)] ROOM was shown at the `climax> of the tour of the `house>.",
        "",
    ),
    17: (
        "社",
        "COMPANY",
        "シャ, やしろ",
        "The COMPANY that built `alter>s were `dirt> poor, [so uses a blue rickSHAW (シャ) to deliver them].",
        "",
    ),
    18: (
        "弱",
        "WEAK",
        "ジャク, よわ-い, よわ-まる, よわ-る, よわ-める",
        "The two `bow>s were WEAKened by the `ice> that had formed on them [even after blue-fingered JACK (ジャク) had remove it].",
        "",
    ),
    19: (
        "首",
        "NECK; head",
        "シュ, くび",
        "The moose HEAD hanging on the wall still had its `horns> and `nose> but stopped at the NECK; [we like to hang our blue SHOEs (シュ) on it].",
        "",
    ),
    20: (
        "秋",
        "AUTUMN",
        "シュウ, あき",
        "In the AUTUMN the remaining `wheat> is set on `fire> to prepare for next year. [It is also the time to buy new blue SHOEs (シュウ) for the new school year].",
        "",
    ),
}
