cards = {
    1: (
        "一",
        "ONE",
        "イツ, イチ, ひと-つ, ひと",
        "If you hold ONE finger horizontally for too long [it will start to ITCH (イチ)].",
        "One",
    ),
    2: (
        "右",
        "RIGHT",
        "ユウ, みぎ",
        "[In shock over the illegal U-turn (ユウ)], he covered his `mouth> with his hand from the RIGHT `side>.",
        "",
    ),
    3: (
        "雨",
        "RAIN",
        "ウ, あま, あめ",
        "[If you take the blue U-Boot (ウ) to AMErika (あめ), then you won’t notice the RAIN]. They know it’s RAINING when the `one> `towel> they hang out is covered in `drop>s.",
        "Rain",
    ),
    4: (
        "円",
        "CIRCLE, YEN",
        "エン, まる-い",
        "Get CIRCULAR YEN coins from a teller's window [and put the special ones in the blue ENvelope (エン)].",
        "",
    ),
    5: (
        "王",
        "KING",
        "オウ",
        # TODO:  heisig for |
        "The KING binds the `three> entities of state together, so [when he died, everyone screamed OH (オウ), no!]",
        "Jewel",
    ),
    6: (
        "音",
        "SOUND",
        "イン, オン, ね, おと",
        "The SOUND that [my blue ONkel (オン) from INdia (イン)] makes when he `stands> on the `sun> was truly horrible.",
        "Sound",
    ),
    7: (
        "下",
        "BELOW",
        "ゲ, カ, もと, さ-がる, くだ-す, お-ろす, しも, さ-げる, くだ-る, くだ-さる, した, お-りる",
        "The T-bar with the droopy LOWER handle is of such INFERIOR quality that [it broke off and fell on the blue KAr (カ)] BELOW.",
        "",
    ),
    8: (
        "火",
        "FIRE",
        "カ, ひ, ほ",
        "Flames of FIRE [shot out of the blue KAr (カ). 'HI (ひ), hi, hi' chuckled the arsonist].",
        "Fire",
    ),
    9: (
        "花",
        "FLOWER",
        "カ, はな",
        "[HANA (はな) called to her friend KAli (カ) 'look at how the blue] `FLOWER> has `change>d.'",
        "Flower",
    ),
    10: (
        "学",
        "STUDY",
        "ガク, まな-ぶ",
        "In the `schoolhouse>, the `child>ren STUDY [GArlic COOking (ガク) and practice with a blue pot].",
        "",
    ),
    11: (
        "気",
        "SPIRIT",
        "ケ, キ",
        "[If you put the big blue KEY (キ)] in the keyhole of the `wheat sheaf>, a SPIRIT-like `steam> will be released into the ATMOSPHERE.",
        "",
    ),
    12: (
        "九",
        "NINE",
        "ク, キュウ, ここの-つ, ここの",
        "The NINE players of the baseball team [use a blue snooker キュウ to practice with].",
        "Baseball",
    ),
    13: (
        "休",
        "REST",
        "キュウ, やす-む",
        "The `person> RESTs against the [CUte (キュウ) blue `tree>] on her DAY OFF.",
        "",
    ),
    14: (
        "金",
        "GOLD",
        "キン, コン, かね, かな",
        "[The blue] `KINg> [(キン)] shelters his `drop>s of GOLD under his `umbrella>.",
        "Metal",
    ),
    15: (
        "空",
        "EMPTY",
        "クウ, そら, あ-ける, あ-く, から",
        "I `craft> a `hole> in the roof's `I-beam> to see the EMPTY SKY, but instead [I see a big KUH-loud (クウ) in the blue].",
        "",
    ),
    16: (
        "月",
        "MOON",
        "ガツ, ゲツ, つき",
        "A pitted crescent MOON shone down on them. [As she GETS (ゲツ) closer to him, she whispers 'Do you have the GUTS (ガツ) to go to the graveyard in the blue moonlight?'].",
        "Flesh",
    ),
    17: (
        "犬",
        "DOG",
        "ケン, いぬ",
        "[KEN (ケン) the blue Chihuahua] is just a `drop> compared to the `St. Bernard> DOG.",
        "Chihuahua",
    ),
    18: (
        "見",
        "SEE",
        "ケン, み-る, み-せる, み-える",
        "[KEN (ケン) is lying on the floor all covered in blue paint.] All I can SEE with my `eye>s is his `human legs> sticking out.",
        "",
    ),
    19: (
        "五",
        "FIVE",
        "ゴ, いつ, いつ-つ",
        "On this strange chair with FIVE legs [the blue cover doubles as a GO (ゴ) board].",
        "",
    ),
    20: (
        "口",
        "MOUTH",
        "ク, コウ, くち",
        "[Saying 'KUCHI KUCHI (くち) KUU (コウ)' to a blue baby] makes it OPEN its MOUTH with delight.",
        "Mouth",
    ),
}
