cards = {
    1: (
        "走",
        "to RUN",
        "ソウ, はし-る",
        "RUNNING across the `soil> `mends> the [blue SOUl (ソウ)].",
        "",
    ),
    2: (
        "草",
        "GRASS",
        "ソウ, くさ",
        "When the `flowers> start growing `early> in the GRASS [it soothes the blue SOUl (ソウ)].",
        "",
    ),
    3: (
        "多",
        "MANY",
        "タ, おお-い",
        "MANY `moons> ago, [I had a room full of blue TAtami (タ)].",
        "",
    ),
    4: (
        "太",
        "FAT; thick",
        "タ, タイ, ふと-る, ふと-い",
        "The `drop> of swaet fell off the `large> FAT man [as he sat of the blue FUTOn (ふと)].",
        "",
    ),
    5: (
        "体",
        "BODY",
        "タイ, テイ, からだ",
        "The `person> [with a blue TIE (タイ)] bought a `book> on how to get the perfect BODY.",
        "",
    ),
    6: (
        "台",
        "PEDESTAL; platform",
        "タイ, ダイ ",
        "[The guy in the blue TIE (タイ)] `elbow>ed the other guy in the `mouth> when trying to get on the PEDESTAL.",
        "",
    ),
    7: (
        "地",
        "GROUND; land",
        "ジ, チ",
        "The `scorpion> scuttled around on the `ground> [trying to avoid the blue CHIckens (チ)].",
        "",
    ),
    8: ("池", "POND; reservoir", "チ, いけ", "[The blue CHIckens (チ) and] the `scorpions> drank `water> from the POND.", ""),
    9: ("知", "to KNOW", "チ, し-る", "[The blue CHIckens (チ)] KNOW how to carry `dart>s in their `mouth>es.", ""),
    10: ("竹", 'BAMBOO; "bamboo" radical', "チク, たけ", "[The blue CHICK (チク)] weaved its way between two BAMBOO. ", ""),
    11: ("茶", "TEA; LIGHT BROWN; チャ sound", "チャ, サ, ", "", ""),
    12: ("昼", "daytime; MIDDAY", "チュウ, ひる", "", ""),
    13: (
        "長",
        'LONG; growth; senior; strong point; "long" radical',
        "チョウ, なが-い",
        "",
        "",
    ),
    14: ("鳥", 'BIRD; "bird" radical', "チョウ, とり", "", ""),
    15: ("朝", "MORNING; dynasty; KOREA (esp. NORTH)", "チョウ, あさ", "", ""),
    16: (
        "通",
        "to PASS; communicate; common; know thoroughly; STREET; counter for ways and letters; frequent a place; in accordance with",
        "ツ, ツウ, とお-る, かよ-う, とお-す",
        "",
        "",
    ),
    17: ("弟", "YOUNGER BROTHER; apprentice", "ダイ, テイ, デ, おとうと", "", ""),
    18: ("店", "shop, STORE; stall", "テン, みせ", "", ""),
    19: ("点", "POINT, dot; counter for articles; to LIGHT", "テン, ", "", ""),
    20: ("電", "ELECTRICITY", "デン, ", "", ""),
}
