cards = {
    1: (
        "二",
        "TWO",
        "ニ, ふた, ふた-つ",
        "TWO fingers held horizontally [over the KNEE (ニ) during the FOOTER (ふた)].",
        "",
    ),
    2: (
        "日",
        "DAY; SUN",
        "ニチ, ジツ, ひ, か",
        "[The HEAt (ひ)] of the SUN powers [NIETZSCHE’s (ニチ) blue CAr (か)] during the DAY.",
        "Sun/day",
    ),
    3: (
        "入",
        "ENTER",
        "ニュウ, い-る, はい-る, い-れる",
        "[The NEW (ニュウ)] person ENTERed backwards much to everyone's [IRUtation (い-る)].",
        "Enter",
    ),
    4: (
        "年",
        "YEAR",
        "ネン, とし",
        "At the end of the YEAR, [I sent TOSHI a blue NENgajo with a picture] of a `horse> in `broken sunglasses>.",
        "",
    ),
    5: (
        "白",
        "WHITE",
        "ビャク, ハク, しろ, しろ-い, しら",
        "A `drop> of `sun> shines WHITE on [the HACKsaw (ハク) blade].",
        "White/dove",
    ),
    6: (
        "八",
        "EIGHT",
        "ハチ, や, やっ-つ, や-つ, よう",
        "The EIGHT [blue eggs are still to HACHI (はち)].",
        "",
    ),
    7: (
        "百",
        "HUNDRED",
        "ヒャク",
        "Ninety-nine is call the `white> year because it is `one> less than a HUNDRED.",
        "",
    ),
    8: (
        "文",
        "SENTENCE",
        "ブン, モン, ふみ",
        "[Blue-haired MONica (モン)] wrote a SENTENCE about a man wearing a `top hat> and a shirt crisscrossed with plaid.",
        "Plaid",
    ),
    9: (
        "木",
        "TREE, WOOD",
        "モク, ボク, こ, き",
        "[Gintoki attacked the KEY-hole (き) with his BOKUto (ボク)] made from the WOOD of the golden TREE.",
        "Tree",
    ),
    10: (
        "本",
        "BOOK",
        "ホン, もと",
        "BOOK pages are made from slices of `wood> cut and read [under the blue skies of HONolulu (ホン)].",
        "",
    ),
    11: (
        "名",
        "NAME",
        "メイ, ミョウ, な",
        "In the `evening>, [Blue-haired MEI (メイ)] calls her lover's NAME with her `mouth>.",
        "",
    ),
    12: (
        "目",
        "EYE",
        "ボク, モク, ま, め",
        "The sideways EYE painted on [the blue MElon (め) seemed to MOCK (モク) people].",
        "Eye",
    ),
    13: (
        "立",
        "STAND up",
        "リツ, リュウ, た-つ, た-てる",
        "[The maid in blue went around the RITZ (リツ)] STANDing up all the vases.",
        "Vase",
    ),
    14: (
        "力",
        "POWER",
        "リョク, リキ, ちから",
        "[RICKY (リキ) turned blue] from all the effort of showing off the POWER of his muscles.",
        "Muscle",
    ),
    15: (
        "林",
        "GROVE",
        "リン, はやし",
        "[Blue-haired RINgo (リン)] was the only person who called the two `trees> (木) in his front yard a GROVE.",
        "",
    ),
    16: (
        "六",
        "SIX",
        "ロク, む-つ, むい, む, むっ-つ",
        "[They used the blue ROCK (ロク)] as a die because it had SIX sides.",
        "",
    ),
    17: (
        "引",
        "PULL",
        "イン, ひ-ける, ひ-く",
        "He PULLed the `bow> back and fired the `walking stick> [INto (イン) the blue yonder].",
        "",
    ),
    18: (
        "雲",
        "CLOUD",
        "ウン, くも",
        "The `rising clouds> form a big `rain> CLOUD [that, out of the blue, rains on those UNderneath (ウン)].",
        "",
    ),
    19: (
        "遠",
        "DISTANT",
        "エン, オン, とお-い",
        "A DISTANT figure on the `road> looks like he is coming [TOOwards (とお-い)] us carrying a `lidded crock> wrapped in a `scarf>.",
        "",
    ),
    20: (
        "何",
        "WHAT",
        "カ, なん, なに",
        "WHAT `can> a `person> say to [a dear blue haired NANNY (なに) driving a KAr (カ)]?",
        "",
    ),
}
