cards = {
    1: (
        "正",
        "CORRECT",
        "ショウ, セイ, まさ, ただ-す, ただ-しい",
        "[Whenever SEIji (セイ) feels blue he dances] on the `ceiling>, done CORRECTly he places `footprint>s on the `ceiling>.",
        "",
    ),
    2: (
        "生",
        "LIFE, grow, birth",
        "ショウ, セイ,う-む, は-える, き, い-かす, う-まれる, お-う, は-やす, い-きる, なま, い-ける",
        "A `drop> when they `grow> gives the flowers enough LIFE [for the SHOW (ショウ) they SEI (セイ)].",
        "Cell",
    ),
    3: (
        "青",
        "BLUE",
        "セイ, ショウ, あお-い, あお",
        "[They SEI (セイ) that] the `moon> appears like BLUE cheese when `grow>ing [which SHOWs (ショウ) they cannot be believed].",
        "",
    ),
    4: (
        "夕",
        "EVENING",
        "セキ, ゆう",
        "A clear moon indicates that EVENING has arrived. [And YOU (ゆう) celebrate with some apres-SKI (セキ)].",
        "Evening",
    ),
    5: (
        "石",
        "STONE",
        "シャク, セキ, コク, いし",
        "A great STONE was rolled in front of the mouth of the cliffside cave [by ISHI (いし) on his blue SKI (セキ) mobile].",
        "Stone",
    ),
    6: (
        "赤",
        "RED",
        "セキ, シャク, あか, あか-らむ, あか-い, あか-らめる",
        "The `ground> was RED where the two blood `drops> fell off the `dagger>. [I hid the mess under my blue SKI (セキ)].",
        "",
    ),
    7: (
        "千",
        "THOUSAND",
        "セン, ち",
        "'A picture of ten eye-droppers is worth a THOUSAND words,' [said the SENator (セン) in the blue suit].",
        "",
    ),
    8: (
        "川",
        "RIVER",
        "セン, かわ",
        "The three streams flow down and joins the RIVER [SEN (セン)].",
        "Stream/flood",
    ),
    9: (
        "先",
        "BEFORE, last",
        "セン, さき",
        "BEFORE the panto `cow> goes on we put hooves on our `human legs> last. [That is common SENse (セン)].",
        "",
    ),
    10: (
        "早",
        "QUICK, early",
        "サッ, ソウ, はや-める, はや-まる, はや-い",
        "Judging from the early `sun>light on the sunflower, it must be `ten> already. Time goes by QUICKLY [when you are SEWing (ソウ) a blue quilt].",
        "Sunflower",
    ),
    11: (
        "足",
        "LEG",
        "ソク, あし, た-る, た-りる, た-す",
        "It took some `mending> after he put his whole LEG in his `mouth> [including his blue SOCKs (ソク)].",
        "Wooden leg",
    ),
    12: (
        "村",
        "VILLAGE",
        "ソン, むら",
        "The `tree>s by the VILLAGE all had `glue> on them after [SONia (ソン) put up the blue posters].",
        "",
    ),
    13: (
        "大",
        "LARGE",
        "タイ, ダイ, おお-きい, おお, おお-いに",
        "[Welsh DAI (ダイ) his blue TAI (タイ)] spreads his arms wide to hug the LARGE St. Bernard dog.",
        "St. Bernard dog",
    ),
    14: (
        "男",
        "MAN",
        "ナン, ダン, おとこ",
        "Working in the `rice field>s requires a MAN with `muscles>, [DAN (ダン) is your go to guy].",
        "",
    ),
    15: (
        "中",
        "MIDDLE, IN",
        "チュウ, ジュウ, なか",
        "He wedges his `walking stick> IN to open the `mouth> so he could get [blue CHEWing (チュウ) gum] IN the MIDDLE.",
        "",
    ),
    16: (
        "虫",
        "INSECT",
        "チュウ, むし",
        "The INSECT's `middle> was pinned in place by [blue CHEWing (チュウ) gum].",
        "",
    ),
    17: (
        "町",
        "TOWN",
        "チョウ, まち",
        "For the `street sign> by the `rice field> pointing to TOWN was [blue paint was CHOsen (チョウ)].",
        "",
    ),
    18: (
        "天",
        "HEAVENS, sky",
        "テン, あま, あめ",
        "The `St. Bernard> couldn't see the HEAVENS because of the ceiling [of the blue AMErican (あめ) TENt (テン)].",
        "",
    ),
    19: (
        "田",
        "RICE FIELD",
        "デン, た",
        "[When the DENtist (デン) feels blue], he strolls along the paths that cross the RICE FIELD.",
        "Rice field",
    ),
    20: (
        "土",
        "SOIL",
        "ト, ド, つち",
        "`Ten> tonnes of SOIL piled up on the `ground> [was peed on by the DOgs (ド)].",
        "Dirt",
    ),
}
