cards = {
    1: (
        "校",
        "SCHOOL, proof-read, exam",
        "コウ",
        "The dads `mingle> by the `tree> outside the SCHOOl [examining their blue COAts (コウ)].",
        "One",
    ),
    2: (
        "左",
        "LEFT",
        "サ, ひだり",
        "[Dressed in a blue SAri (サ)], she grabbed the `I-beam> with her LEFT hand and placed it by her `side>. ",
        "",
    ),
    3: (
        "三",
        "THREE",
        "サン, み-つ, み, みっ-つ",
        "The THREE horizontal lines in the [blue SANd (サン) were drawn by ME (み)].",
        "",
    ),
    4: (
        "山",
        "MOUNTAIN",
        "サン, やま",
        "This is the triple-peaked MOUNTAIN from which one can see Fuji-SAN (サン)].",
        "Mountain",
    ),
    5: (
        "子",
        "CHILD",
        "ス, シ, こ",
        "A long-armed CHILD [named SUE (ス) is lying on a blue COtton (こ) SHEet (シ)].",
        "Child",
    ),
    6: (
        "四",
        "FOUR",
        "シ, よ-つ, よん, よ, よっ-つ",
        "The FOUR corners of the square were supposed to be marked, but [SHE (シ) gave up after two].",
        "Four",
    ),
    7: (
        "糸",
        "THREAD",
        "シ, いと",
        "The length of THREAD is laid out on a [blue SHEet (シ)].",
        "Thread",
    ),
    8: (
        "字",
        "CHARACTER",
        "ジ, あざ",
        "The `child> in the `house> writes the CHARACTERs for its name over and over [in a GEneric (ジ) blue].",
        "",
    ),
    9: (
        "耳",
        "EAR",
        "ジ, みみ",
        "This EAR looks just like the one on my [blue robot MIMI (みみ)].",
        "",
    ),
    10: (
        "七",
        "SEVEN",
        "シチ, なの, なな-つ, なな",
        "[NANA (なな) pressed the blue SWITCHy (シチ)] and the SEVEN turned upside down.",
        "",
    ),
    11: (
        "車",
        "CAR",
        "シャ, くるま",
        "[He saw a blue two-wheeled rickSHAW (シャ)] and decided to make it into a CAR.",
        "Car",
    ),
    12: (
        "手",
        "HAND",
        "シュ, て, た",
        "A HAND with fingers spread out to [SHU (シュ) away the blue bottle].",
        "Hand",
    ),
    13: (
        "十",
        "TEN",
        "ジュウ, ジッ, と, とお",
        "He was cross because hist TEN [TOEs (とお) had turned blue].",
        "Needle",
    ),
    14: (
        "出",
        "EXIT",
        "スイ, シュツ, だ-す, で-る",
        "[When I DARE (でる)] to EXIT from [behind the bamboo SHOOTS (シュツ)], I see `mountain> upon `mountain>.",
        "",
    ),
    15: (
        "女",
        "WOMAN",
        "ニョウ, ニョ, ジョ, め, おんな",
        "The WOMAN spread her arms to [grab the blue JO (ジョ)].",
        "Woman",
    ),
    16: (
        "小",
        "LITTLE",
        "ショウ, ちい-さい, お, こ",
        "The three LITTLE `drops> [SHOwed (ショウ) up on the blue CHEese's SIde (ちい-さい)].",
        "Little",
    ),
    17: (
        "上",
        "ABOVE",
        "ショウ, ジョウ, のぼ-す, うえ, かみ, あ-がる, のぼ-せる, うわ, あ-げる, のぼ-る",
        "The `wand> stood upright ABOVE the `floor> and [was SHOwing (ショウ) off in front of 'OOEver (うえ) was present].",
        "",
    ),
    18: (
        "森",
        "FOREST",
        "シン, もり",
        "Running though the FOREST of `tree>s, [MORRIs banged into the branches until his SHINs (シン) were black and blue].",
        "",
    ),
    19: (
        "人",
        "PERSON",
        "ニン, ジン, ひと",
        "The armless PERSON [works as a GINger (ジン) NINja (ニン) while wearing a blue gi].",
        "Person",
    ),
    20: (
        "水",
        "WATER",
        "スイ, みず",
        "The alpine WATER [shimmers blue as it flows through SWIss (スイ) rivers].",
        "Water",
    ),
}
