cards = {
    1: (
        "合",
        "FIT; combine",
        "ガッ, ゴウ, カッ, あ-う, あ-わせる, あ-わす",
        "There was not enough room at the `meeting> to FIT more than one big `mouth> in, so [the one in blue had to GO (ゴウ)].",
        "",
    ),
    2: (
        "谷",
        "VALLEY",
        "コク, たに",
        "[NakaTANI (たに) came from a small] VALLEY where every `mouth> says when `going in> take an `umbrella>.",
        "",
    ),
    3: (
        "国",
        "COUNTRY",
        "コク, くに",
        "The COUNTRY's prize `jewel> was `walled in> to protect it [from the blue COCKatiels (コク)].",
        "",
    ),
    4: (
        "黒",
        "BLACK",
        "コク, くろ-い, くろ",
        "The `computer> was charred BLACK by the `oven fire> [set by the blue COCKatiels (コク)].",
        "",
    ),
    5: (
        "今",
        "NOW",
        "キン, コン, いま",
        "The `clock hands> showed that the `meeting> was starting NOW; [I was CONcerned (コン) I was late].",
        "",
    ),
    6: (
        "才",
        "GENIUS",
        "サイ",
        "The GENIUS showed he could do it with one finger and [the crowd SIGHed (サイ) in amazement].",
        "",
    ),
    7: (
        "作",
        "MAKE",
        "サク, サ, つく-る",
        "The `person> used a 'saw> to MAKE it but [it still SUCKed (サク)].",
        "",
    ),
    8: (
        "算",
        "CALCULATION",
        "サン",
        "Using the `bamboo> and `both hands>, in front of my `eye>s he created an abacus for the CALCULATION [of how much blue SANd (サン) we would need .",
        "",
    ),
    9: (
        "止",
        "STOP",
        "シ, と-める, と-まる",
        "When he can to a sudden STOP, he left a footprint [on the blue SHEet (シ)].",
        "Footprint",
    ),
    10: (
        "市",
        "CITY; MARKET",
        "シ, いち",
        "Dressed only in only a bath `towel> and 'top hat> he rushed to the CITY MARKET [to buy a blue SHEet (シ)].",
        "",
    ),
    11: (
        "思",
        "THINK; remember",
        "シ, おも-う",
        ".",
        "",
    ),
    12: (
        "紙",
        "PAPER",
        "シ, かみ",
        ".",
        "",
    ),
    13: (
        "寺",
        "BUDDIST TEMPLE",
        "ジ, てら",
        ".",
        "",
    ),
    14: (
        "自",
        "ONESELF",
        "シ, ジ, みずか-ら",
        ".",
        "",
    ),
    15: (
        "時",
        "TIME",
        "ジ, とき",
        ".",
        "",
    ),
    16: (
        "室",
        "ROOM",
        "シツ, むろ",
        ".",
        "",
    ),
    17: (
        "社",
        "COMPANY",
        "シャ, やしろ",
        ".",
        "",
    ),
    18: (
        "弱",
        "WEAK",
        "ジャク, よわ-い, よわ-まる, よわ-る, よわ-める",
        ".",
        "",
    ),
    19: (
        "首",
        "NECK; head",
        "シュ, くび",
        ".",
        "",
    ),
    20: (
        "秋",
        "AUTUMN",
        "シュウ, あき",
        ".",
        "",
    ),
}
