cards = {
    1: (
        "科",
        "DEPARTMENT",
        "カ",
        "The DEPARTMENT staff used the `measuring cups> to [fill the director's blue CAr (カ)] with `wheat>.",
        "",
    ),
    2: (
        "夏",
        "SUMMER",
        "ゲ, カ, なつ",
        "During the SUMMER, they get it into their `head>s that `walking legs> are [quicker than a blue CAr (カ). I think they are NUTS (なつ)].",
        "",
    ),
    3: (
        "家",
        "HOUSE, FAMILY",
        "ケ, カ, や, いえ",
        "[Blue-haired KEvin's (ケ)] FAMILY `HOUSE> looks fancy from the outside but the `sow> has wrecked the inside.",
        "",
    ),
    4: (
        "歌",
        "SONG",
        "カ, うた, うた-う",
        "[Blue-haired UTA (うた)] `yawn>s while leading the `can>-`can> girls in a SONG.",
        "",
    ),
    5: (
        "画",
        "BRUSH-STROKE, picture",
        "カク, ガ",
        "[Blue-haired GArfield (ガ)] paints a `sprout> on the `ceiling> with BRUSH-STROKEs as wide as a `shovel>.",
        "",
    ),
    6: (
        "回",
        "-TIMES",
        "エ, カイ, まわ-す, まわ-る",
        "[To build the blue KIte (カイ), the Expert (エ)] said to make this square nut go around the square bolt at least ten TIMES.",
        "",
    ),
    7: (
        "会",
        "MEETING",
        "エ, カイ, あ-う",
        "['OW (あ-う)!' he said] when bumping into the `wall> at the `MEETING>.",
        "",
    ),
    8: (
        "海",
        "OCEAN",
        "カイ, うみ",
        "`Every> single `drop of water> ends up in the OCEAN [according to blue-haired KAI (カイ)].",
        "",
    ),
    9: (
        "絵",
        "PICTURE",
        "エ, カイ",
        "At the `meeting>, [the blue-haired twins KAI (カイ) and Emile (エ)] made a wonderful PICTURE out coloured `thread>s.",
        "",
    ),
    10: (
        "貝",
        "SHELLFISH",
        "かい",
        "A SHELLFISH totters around on its 'little legs>. [KAInda (かい) cute, I suppose].",
        "Clams (money)",
    ),
    11: (
        "",
        "",
        "",
        ".",
        "",
    ),
    12: (
        "",
        "",
        "",
        ".",
        "",
    ),
    13: (
        "",
        "",
        "",
        ".",
        "",
    ),
    14: (
        "",
        "",
        "",
        ".",
        "",
    ),
    15: (
        "",
        "",
        "",
        ".",
        "",
    ),
    16: (
        "",
        "",
        "",
        ".",
        "",
    ),
    17: (
        "",
        "",
        "",
        ".",
        "",
    ),
    18: (
        "",
        "",
        "",
        ".",
        "",
    ),
    19: (
        "",
        "",
        "",
        ".",
        "",
    ),
    20: (
        "",
        "",
        "",
        ".",
        "",
    ),
}
