cards = {
    1: (
        "春",
        "SPRINGTIME",
        "シュン, はる",
        "In the SPRINGTIME, [blue-haired SHUNpei (シュン)] planted the `bonsai> out in the `sun>.",
        "",
    ),
    2: (
        "書",
        "WRITE",
        "ショ, か-く",
        "[Blue-haired SHOlto (ショ)] WRITEs down the word of the `day> with his `brush>.",
        "",
    ),
    3: (
        "少",
        "FEW; a little; young",
        "ショウ, すこ-し, すく-ない",
        "[On the blue SHOUlder (ショウ)] he placed a FEW `little> drops with the `eyedropper>.",
        "",
    ),
    4: (
        "場",
        "LOCATION; place; occasion; scene; market",
        "ジョウ, ば",
        "[Blue-haired JOE (ジョウ)] hid the LOCATION of the `piggy bank> by covering it with `dirt>.",
        "",
    ),
    5: (
        "色",
        'COLOUR; facial expression or tone',
        "ショク, シキ, いろ",
        "[The SHOCKingly (ショク) blue] COLOUR of the `mosaic> was `bound> up in a bag.",
        "",
    ),
    6: (
        "食",
        "EAT; FOOD, dish, meal",
        "ジキ, ショク, た-べる, く-らう, く-う",
        "[The SHOCKingly (ショク) blue] `umbrella> was held over the `good> FOOD before it was time to EAT.",
        "Eating/food",
    ),
    7: (
        "心",
        "HEART, mind; center",
        "シン, こころ",
        "[His SHINs (シン) turned blue] when his HEART stopped beating.",
        "Heart",
    ),
    8: (
        "新",
        "NEW",
        "シン, あたら-しい, にい, あら-た",
        "[He banged his SHINs (シン) blue] against his NEW `axe> when running to get the `red pepper>.",
        "",
    ),
    9: (
        "親",
        "PARENT; relatives; intimate; friendly",
        "シン, した-しい, おや, した-しむ",
        "[He banged his SHINs (シン) blue] in the excitement of `see>ing the `red pepper> his PARENTs found.",
        "",
    ),
    10: (
        "図",
        "MAP; ILLUSTRATION; plan",
        "ズ, ト, はか-る",
        "Without a MAP to guide them, the no longer `pent in> [blue painted ZUlu (ズ) people] had to guide themselves using the `big dipper>.",
        "",
    ),
    11: (
        "数",
        "NUMBER; several; to COUNT",
        "ス, スウ, かず, かぞ-える",
        "[Blue-clad SUE (スウ)] and the other `woman> were told to COUNT the NUMBER of `rice> by the `taskmaster>.",
        "",
    ),
    12: (
        "西",
        "WEST; Spain",
        "セイ, サイ, にし",
        "[Blue-haired SEIko (セイ) ] put her `legs> through the `ceiling> when pointing out which was WEST from the `four> directions.",
        "",
    ),
    13: (
        "声",
        "VOICE; sound; reputation",
        "ショウ, セイ, こえ, こわ",
        "The `samurai> was trying to sell [blue SEIko (セイ) watches] by singing in his beautiful VOICE and waving his `two coloured flag>.",
        "",
    ),
    14: (
        "星",
        "STAR; celestial body",
        "セイ, ショウ, ほし",
        "[The blue SEIko (セイ) watches] could show the position of the `sun> and STARs, and also the `life>signs of the wearer.",
        "",
    ),
    15: (
        "晴",
        "to CLEAR UP; good weather; formal, gala",
        "セイ, は-れる, は-らす",
        "[According to blue-haired SEIko (セイ)]the sky was starting to CLEAR UP, so the `sun> and patches of `blue> would soon be visible.",
        "",
    ),
    16: (
        "切",
        "to CUT; be very close; SHARP; indication of the end; finish doing",
        "サイ, セツ, き-れる, き-る",
        "[SAImon (サイ)] with `seven> CUTs of his `dagger> sliced and diced.",
        "",
    ),
    17: (
        "雪",
        "SNOW",
        "セツ, ゆき",
        "[According to YUKI (ゆき)] the `rain> had turned to SNOW and, thus, required a `broom> to remove.",
        "",
    ),
    18: (
        "船",
        "SHIP",
        "セン, ふな, ふね",
        "[The blue-suited SENator (セン)] stepped from the small `boat> he took from the `gully> onto the SHIP.",
        "",
    ),
    19: (
        "前",
        "IN FRONT; before",
        "ゼン, まえ",
        "[The blue-robed ZEN priest] watched as the butcher, IN FRONT of him, hacked the animal's `horns> off the `flesh> with his `knife>.",
        "",
    ),
    20: (
        "組",
        "GROUP; class; to FORM, COMBINE; ASSOCIATION",
        "ソ, く-む, くみ",
        "[Blue-haired KUMIko (くみ)] GROUPed the `thread>s together an placed them on the `shelf>.",
        "",
    ),
}
