cards = {
    1: (
        "走",
        "to RUN",
        "ソウ, はし-る",
        "RUNNING across the `soil> `mends> the [blue SOUl (ソウ)].",
        "",
    ),
    2: (
        "草",
        "GRASS",
        "ソウ, くさ",
        "When the `flowers> start growing `early> in the GRASS [it soothes the blue SOUl (ソウ)].",
        "",
    ),
    3: (
        "多",
        "MANY",
        "タ, おお-い",
        "MANY `moons> ago, [I had a room full of blue TAtami (タ)].",
        "",
    ),
    4: (
        "太",
        "FAT; thick",
        "タ, タイ, ふと-る, ふと-い",
        "The `drop> of sweat fell off the `large> FAT man [as he sat of the blue FUTOn (ふと)].",
        "",
    ),
    5: (
        "体",
        "BODY",
        "タイ, テイ, からだ",
        "The `person> [with a blue TIE (タイ)] bought a `book> on how to get the perfect BODY.",
        "",
    ),
    6: (
        "台",
        "PEDESTAL; platform",
        "タイ, ダイ ",
        "[The guy in the blue TIE (タイ)] `elbow>ed the other guy in the `mouth> when trying to get on the PEDESTAL.",
        "",
    ),
    7: (
        "地",
        "GROUND; land",
        "ジ, チ",
        "The `scorpion> scuttled around on the `dirt>y GROUND [trying to avoid the blue CHIckens (チ)].",
        "",
    ),
    8: ("池", "POND; reservoir", "チ, いけ", "[The blue CHIckens (チ) and] the `scorpions> drank `water> from the POND.", ""),
    9: ("知", "to KNOW", "チ, し-る", "[The blue CHIckens (チ)] KNOW how to carry `dart>s in their `mouth>es.", ""),
    10: ("竹", 'BAMBOO; "bamboo" radical', "チク, たけ", "[The blue CHICK (チク)] weaved its way between two BAMBOO. ", ""),
    11: ("茶", "TEA; light brown; チャ sound", "チャ, サ", "[A hot cup of CHA (チャ) made from] the `flower>s of the TEA plant were enjoyed under the `umbrella> on a `wooden pole>.", ""),
    12: ("昼", "daytime; MIDDAY", "チュウ, ひる", "He played the `shakuhachi> from `nightbreak> to MIDDAY [while CHEWing (チュウ) blueberry gum].", ""),
    13: (
        "長",
        'LONG; senior',
        "チョウ, なが-い",
        "The LONG-haired guy [CHOse (チョウ) a blue] `hairpin> to hold it back.",
        "",
    ),
    14: ("鳥", 'BIRD', "チョウ, とり",
         "The BIRD was `white> like a `dove> but `one> feather amongst its `tail feathers> [had CHOsen (チョウ) to turn blue].", ""),
    15: ("朝", "MORNING; Korea (esp. North)", "チョウ, あさ", "The `moon> fades like `mist> as the MORNING [CHOoses (チョウ) to begin]. ", ""),
    16: (
        "通",
        "TRAFFIC; to pass through",
        "ツ, ツウ, とお-る, かよ-う, とお-す",
        "With a `chop-seal> carved using a `screwdriver> [and a yippee-KAYOU (かよ-う)] he stamped his approval to allow the TRAFFIC to pass down the `road>.",
        "",
    ),
    17: ("弟", "YOUNGER BROTHER", "ダイ, テイ, デ, おとうと", "[OTTO ()], my YOUNGER BROTHER used to wear `horns> on his head and a `dollar sign> around his neck.", ""),
    18: ("店", "SHOP, store; stall", "テン, みせ", "The `fortune-teller> set up SHOP in a `cave> [selling blue TENnis (テン) balls].", ""),
    19: ("点", "SPOT; point; dot", "テン", "The `fortune-teller> stared at the `fire> until SPOTS [the size of TENnis (テン) balls] appeared in her eyes.", ""),
    20: ("電", "ELECTRICITY", "デン", "During the `rain> storm ELECTRICITY pierced the `field> like a `fishhook> [leaving a huge DENt (デン)].", ""),
}
